[package]
name = "foam-up"
version = "0.1.0"
authors = ["Jan Schulte <jan@work-with-jan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
serde = "1.0.126"
serde_json = "1.0.64"